# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git' 
platform :ios, '14.0'

target 'PageExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PageExample
  pod 'RxSwift'
  pod 'RxCocoa'

  target 'PageExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PageExampleUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
